### PR TITLE
Add fan side URL campaign page

### PR DESCRIPTION
**Pull request by wildmouse**
- Add URL campaign page 
- Update campaign URL for new routing

### CODE REVIEW

**Comment by toshiakitakase** [comment]
I received the following error message when generating a campaign.
This error occurs after the campaign has been configured and the transaction to the contract has succeeded.

URL:
http://localhost:3000/dashboard/0xaff4481d10270f50f203e0763e2597776068cbc5/distributors/0x360557300e0b373bdb451f07fa292320cc4df136

Error:
Screen Shot 2021-02-03 at 18 31 57

**Comment by toshiakitakase** [comment]
Find error.

Step
1. Claim token from a wallet address A -> Success
2. Claim button was disabled.
3. Change wallet to address B and reload
4. Claim button is active
5. Try to claim token -> Error

Screen Shot 2021-02-04 at 10 07 32

**Comment by toshiakitakase** [comment]
When using URL Distributor, the text would be better like "This URL campaign has already been claimed.".
Screen Shot 2021-02-04 at 10 16 08

**Comment by wildmouse** [comment]
> I received the following error message when generating a campaign.
> This error occurs after the campaign has been configured and the transaction to the contract has succeeded.
> 
> URL:
> http://localhost:3000/dashboard/0xaff4481d10270f50f203e0763e2597776068cbc5/distributors/0x360557300e0b373bdb451f07fa292320cc4df136
> 
> Error:
> Screen Shot 2021-02-03 at 18 31 57

This bug is not inserted in this PR, fixed in #174

**Comment by wildmouse** [comment]
Fixed other comments.

**Review by toshiakitakase — APPROVED** [review]
LGTM

**Pull request merged**
