### PR TITLE
Delete Audius distributor

### PR DESCRIPTION
**Pull request by toshiakitakase**

### CODE REVIEW

**Comment by wildmouse** [comment]
Create audius page is shown when I access following URL directly. 
http://localhost:3000/dashboard/0xd92e713d051c37ebb2561803a3b5fbabc4962431/distributors/0x590b4465a94be635bf2f760025c61ec3680f687c

Is it not possible to delete audius distributor object from `distributors` ?  
https://github.com/iroiro/iroiro/blob/cfb821394b65fb181563633ab00e709ea93386cf/frontend/packages/react-app/src/utils/distributors.ts#L15-L26

**Comment by wildmouse** [comment]
Storybook occurs error when trying to show following components with below error: 

> Cannot read property 'distributorMetadata' of undefined


- CampaignListTable

**Comment by toshiakitakase** [comment]
Fixed

**Review by wildmouse — APPROVED** [review]
LGTM 🏃‍♀️

**Pull request merged**
