### PR TITLE
Maoh/update style

### PR DESCRIPTION
**Pull request by MaohDesign**
SP support and I fixed a few problems.

- Add share campaign URL in campaign detail
- Limit the number of description characters
- Add description to campaign detail
- Create a limit on the number of characters that can be entered in the description.
- Only the Medium logo is big.

### CODE REVIEW

**Comment by wildmouse** [comment]
Seems padding should be added to the activity table. 
Screen Shot 2021-02-28 at 10 28 15

**Comment by wildmouse** [comment]
Select token modal is shortened on desktop. 
Screen Shot 2021-02-28 at 10 31 39

**Review by wildmouse — APPROVED** [review]
LGTM 🏃‍♀️

**Review by toshiakitakase — APPROVED** [review]
LGTM

**Pull request merged**
